mitsuba -L error ./cornell-box-point/hetero/time_regular.xml
mitsuba -L error ./cornell-box-point/hetero/time_stratified.xml
mitsuba -L error ./cornell-box-point/hetero/time_uniform.xml
mitsuba -L error ./cornell-box-point/hetero/full_mc.xml
mitsuba -L error ./cornell-box-point/homo/time_regular.xml
mitsuba -L error ./cornell-box-point/homo/time_stratified.xml
mitsuba -L error ./cornell-box-point/homo/time_uniform.xml
mitsuba -L error ./cornell-box-point/homo/full_mc.xml
mitsuba -L error ./cornell-box-point-bounce3/hetero/time_regular.xml
mitsuba -L error ./cornell-box-point-bounce3/hetero/time_stratified.xml
mitsuba -L error ./cornell-box-point-bounce3/hetero/time_uniform.xml
mitsuba -L error ./cornell-box-point-bounce3/hetero/full_mc.xml
mitsuba -L error ./cornell-box-point-bounce3/homo/time_regular.xml
mitsuba -L error ./cornell-box-point-bounce3/homo/time_stratified.xml
mitsuba -L error ./cornell-box-point-bounce3/homo/time_uniform.xml
mitsuba -L error ./cornell-box-point-bounce3/homo/full_mc.xml
mitsuba -L error ./cornell-box-point-bounce4/hetero/time_regular.xml
mitsuba -L error ./cornell-box-point-bounce4/hetero/time_stratified.xml
mitsuba -L error ./cornell-box-point-bounce4/hetero/time_uniform.xml
mitsuba -L error ./cornell-box-point-bounce4/hetero/full_mc.xml
mitsuba -L error ./cornell-box-point-bounce4/homo/time_regular.xml
mitsuba -L error ./cornell-box-point-bounce4/homo/time_stratified.xml
mitsuba -L error ./cornell-box-point-bounce4/homo/time_uniform.xml
mitsuba -L error ./cornell-box-point-bounce4/homo/full_mc.xml
